#!/bin/bash

# $Id: bootstrap,v 1.5 2006-11-20 05:48:59 yselkowitz Exp $

set -e

export CYGPORT_BOOTSTRAP=1

${MAKE} -C ${top_builddir} dist-bzip2

cp -f ${top_builddir}/${PACKAGE}-${VERSION}.tar.bz2 .
cp -f ${top_srcdir}/data/sample.cygport ${PACKAGE}-${VERSION}-1.cygport

${top_builddir}/bin/cygport ${PACKAGE}-${VERSION}-1.cygport prep compile install pkg

cp -r ${PACKAGE}-${VERSION}-1/dist/${PACKAGE} .

${top_builddir}/bin/cygport ${PACKAGE}-${VERSION}-1.cygport finish
