#!/bin/bash

# $Header: /usr/src/cygport/tmp/cygport/test/messages,v 1.3 2006-11-20 03:01:02 yselkowitz Exp $

set -e

export CYGPORT_BOOTSTRAP=1

${top_builddir}/bin/cygport --help
echo

${top_builddir}/bin/cygport --version
echo

cat > foo-1.2.3-4.cygport <<-_EOF
	DESCRIPTION="Cygport messages test package"
	HOMEPAGE="http://cygwinports.dotsrc.org/"
	SRC_URI="http://cygwinports.dotsrc.org/${P}.ABC"
	_EOF

${top_builddir}/bin/cygport foo-1.2.3-4.cygport info
echo

rm -f foo-1.2.3-4.cygport
