#!/bin/bash

set -e

test -d ${top_builddir}/tests || mkdir -p ${top_builddir}/tests
cd ${top_builddir}/tests

rm -f ${PACKAGE}-${VERSION}-1-src.tar.xz ${PACKAGE}-${VERSION}-1.tar.xz

if [ -f ${top_srcdir}/../${PACKAGE}-${VERSION}.tar.gz ]
then
	# running under make distcheck
	# make dist during make distcheck won't work because all files in
	# DISTDIR are read-only
	cp -f ${top_srcdir}/../${PACKAGE}-${VERSION}.tar.gz .
elif [ -f ${top_builddir}/Makefile ] && [ -n "${MAKE}" ]
then
	${MAKE} -C ${top_builddir} dist-gzip > /dev/null
	cp -f ${top_builddir}/${PACKAGE}-${VERSION}.tar.gz .
elif [ -d ${top_srcdir}/.git ]
then
	pushd ${top_srcdir}
	git archive -o ${PACKAGE}-${VERSION}.tar.gz --prefix=${PACKAGE}-${VERSION}/ HEAD
	popd
	cp -f ${top_srcdir}/${PACKAGE}-${VERSION}.tar.gz .
else
	exit 77
fi

cp -f ${top_srcdir}/data/sample.cygport ${PACKAGE}.cygport

${top_builddir}/bin/cygport-inplace ${PACKAGE}.cygport all

rm -f ${PACKAGE}-${VERSION}.tar.gz
