#!/bin/bash

set -e

test -d ${top_builddir}/tests || mkdir -p ${top_builddir}/tests
cd ${top_builddir}/tests

rm -f ${PACKAGE}-${VERSION}-1-src.tar.xz ${PACKAGE}-${VERSION}-1.tar.xz

if [ -f ${top_srcdir}/../${PACKAGE}-${VERSION}.tar.xz ]
then
	# running under make distcheck
	# make dist during make distcheck won't work because all files in
	# DISTDIR are read-only
	cp -f ${top_srcdir}/../${PACKAGE}-${VERSION}.tar.xz .
else
	${MAKE} -C ${top_builddir} dist-xz > /dev/null
	cp -f ${top_builddir}/${PACKAGE}-${VERSION}.tar.xz .
fi

cp -f ${top_srcdir}/data/sample.cygport ${PACKAGE}.cygport

${top_builddir}/bin/cygport-inplace ${PACKAGE}.cygport prep compile install pkg

cp -r ${PACKAGE}-${VERSION}-1/dist/${PACKAGE} .

${top_builddir}/bin/cygport-inplace ${PACKAGE}.cygport finish

rm -f ${PACKAGE}-${VERSION}.tar.xz ${PACKAGE}.cygport
