#!/bin/bash

set -e

export CYGPORT_BOOTSTRAP=1

${top_builddir}/bin/cygport --help
echo

${top_builddir}/bin/cygport --version
echo

cat > foo-1.2.3-4.cygport <<-_EOF
	DESCRIPTION="Cygport messages test package"
	HOMEPAGE="http://sourceware.org/cygwinports/"
	SRC_URI="http://sourceware.org/cygwinports/\${P}.ABC"
	_EOF

${top_builddir}/bin/cygport foo-1.2.3-4.cygport info
echo

rm -f foo-1.2.3-4.cygport
