#!/bin/bash

set -e

test -d ${top_builddir}/tests || mkdir -p ${top_builddir}/tests
cd ${top_builddir}/tests

${top_builddir}/bin/cygport-inplace --help
echo

${top_builddir}/bin/cygport-inplace --version
echo

cat > foo.cygport <<-_EOF
	NAME="foo"
	VERSION=2.3.4
	RELEASE=1
	DESCRIPTION="Cygport messages test package"
	HOMEPAGE="http://sourceware.org/cygwinports/"
	SRC_URI="http://sourceware.org/cygwinports/\${P}.ABC"
	_EOF

${top_builddir}/bin/cygport-inplace foo.cygport info
echo

rm -f foo.cygport
