#!/bin/bash

set -e

test -d ${top_builddir}/testsuite/basic/bootstrap || mkdir -p ${top_builddir}/testsuite/basic/bootstrap
cd ${top_builddir}/testsuite/basic/bootstrap

rm -f ${PACKAGE}-${VERSION}-1-src.tar.xz ${PACKAGE}-${VERSION}-1.tar.xz

if [ -d ${top_srcdir}/.git ]
then
	pushd ${top_srcdir}
	git archive-all --prefix=${PACKAGE}-${VERSION}/ ${PACKAGE}-${VERSION}.tar.gz
	popd
	cp -f ${top_srcdir}/${PACKAGE}-${VERSION}.tar.gz .
else
	exit 77
fi

cp -f ${top_srcdir}/data/sample.cygport ${PACKAGE}.cygport

${top_builddir}/bin/cygport-inplace ${PACKAGE}.cygport all
