#!/bin/bash

set -e

test=$1

test -d ${top_builddir}/testsuite/$test || mkdir -p ${top_builddir}/testsuite/$test
cd ${top_builddir}/testsuite/$test

cp -f ${top_srcdir}/testsuite/$test/* .

${top_builddir}/bin/cygport-inplace *.cygport clean get all

cmp ${top_srcdir}/testsuite/$test/*.list <(${top_builddir}/bin/cygport-inplace *.cygport list)
